#!/bin/bash

sudo apt-get install -y binutils bison libudev-dev screen
# install gvm
bash < <(curl -s -S -L https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer)
source /home/pi/.gvm/scripts/gvm

# install go
gvm install go1.4
gvm use go1.4
export GOROOT_BOOTSTRAP=$GOROOT
gvm install go1.8
gvm use go1.8 --default

mkdir -p ~/go/src
cat << "EOF" >> ~/.profile
export PATH=$PATH:/usr/local/go/bin
export GOPATH=$HOME/go
EOF
source ~/.profile

# cat /proc/bus/input/devices

cd ~/go/src
git clone https://github.com/riking/joycon.git
cd joycon/prog4
go get ./...
cd